FROM python:3

ARG FLASK_DATABASE_URL
ARG PORT
ARG SECRET_KEY
ARG SENDGRID_API_KEY
ARG MAIL_DEFAULT_SENDER
ARG APP_URL

ENV FLASK_DATABASE_URL ${FLASK_DATABASE_URL}
ENV PORT 80
ENV SECRET_KEY ${SECRET_KEY}
ENV SENDGRID_API_KEY ${SENDGRID_API_KEY}
ENV MAIL_DEFAULT_SENDER ${MAIL_DEFAULT_SENDER}
ENV APP_URL ${APP_URL}

COPY requirements.txt /app/requirements.txt

WORKDIR /app

RUN pip install -r requirements.txt

RUN useradd --create-home --shell /bin/bash app_user

COPY . .

USER app_user

CMD [ "bash", "run.sh" ]
